# permissions for end users to edit shootouts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shootout-editor-role
rules:
- apiGroups:
  - example.com
  resources:
  - shootouts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com
  resources:
  - shootouts/status
  verbs:
  - get
